### ISSUE TITLE
adding DOI Links does not work 

### ISSUE THREAD

**Issue by Jack-613** [retorquere/zotero-prosec-linker#2]
Adding DOI Link does not function:

I marked DOI Box

URL: http://doi.org/{DOI}
Title: @-DOI

and started Add-on (with right click) => Title Link was added perfectly however DOI-Link is missing ?

![Bildschirmfoto 2021-05-19 um 17 22 35](https://user-images.githubusercontent.com/84462365/118840350-9b64a880-b8c7-11eb-9620-4860321b272b.png)

**Comment by retorquere** [comment]
I take it this is resolved now?

**Comment by Jack-613** [comment]
Yes, absolutely.
