### ISSUE TITLE
I noticed something with our plug-in that I couldn't explain... with PDF-link

### ISSUE THREAD

**Issue by Jack-613** [retorquere/zotero-prosec-linker#6]
Please forgive me if I ask you an other question, but today I noticed something with our plug-in that I couldn't explain...

I marked two items and ran the plugin simultaneously on both, one worked fine and the other didn't create the PDF link for some reason.

I am sending the PDF's attached. Do you have any idea what this could be ?

Thank you very much !
<img width="739" alt="Bildschirmfoto 2021-05-26 um 19 39 42" src="https://user-images.githubusercontent.com/84462365/119708913-e9942180-be5c-11eb-9c70-8e9bbec1eff0.png">
[Staehlke et al. - 2020 - The Anchorage of Bone Cells onto an Yttria-Stabili.pdf](https://github.com/retorquere/zotero-prosec-linker/files/6548752/Staehlke.et.al.-.2020.-.The.Anchorage.of.Bone.Cells.onto.an.Yttria-Stabili.pdf)
[Soares et al. - 2021 - New, tough and strong lithium metasilicate dental .pdf](https://github.com/retorquere/zotero-prosec-linker/files/6548754/Soares.et.al.-.2021.-.New.tough.and.strong.lithium.metasilicate.dental.pdf)

**Comment by retorquere** [comment]
Can you do the following:

* install 1.0.2.18 
* install https://github.com/retorquere/zotero-debug-log/releases/latest
* Turn on debug logging in the help menu
* reproduce the problem
* Send debug log to file.io from the help menu

An alert will pop up with an alphanumeric ID, I need that.

**Comment by Jack-613** [comment]
I did as you described ID was 

<img width="749" alt="Bildschirmfoto 2021-05-27 um 17 27 09" src="https://user-images.githubusercontent.com/84462365/119853991-f70ae380-bf10-11eb-9753-d334d2664335.png">
hxg0C1oA1elT

**Comment by Jack-613** [comment]
did it and got following id K3XdI8IHntNS

<img width="690" alt="Bildschirmfoto 2021-05-27 um 19 13 34" src="https://user-images.githubusercontent.com/84462365/119868717-b23a7900-bf1f-11eb-8f99-e747d1dcd010.png">

**Comment by Jack-613** [comment]
it worked perfect ! However this is the ID if you need it 

5jcENB5UehpF

Should I remove the Debug Log for Zero Add-One ?

<img width="712" alt="Bildschirmfoto 2021-05-27 um 21 01 17" src="https://user-images.githubusercontent.com/84462365/119882626-e79a9300-bf2e-11eb-802f-99b5f991bb20.png">


thank you so much !

**Comment by retorquere** [comment]
Zero Add-One?
